SET IDENTITY_INSERT [dbo].[Game] ON
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (1, N'God of War', N'Playstation 4', 10)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (2, N'Wii Sports', N'Wii', 82.53)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (3, N'Mario Kart WII', N'Wii', 35.52)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (4, N'Wii Sports Resort', N'Wii', 32.77)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (5, N'Wii Play', N'Wii', 28.92)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (7, N'New Super Mario Bros. Wii', N'Wii', 28.32)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (8, N'Wii Fit', N'Wii', 22.7)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (9, N'Wii Fit Plus', N'Wii', 21.79)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (10, N'Super Smash Bros. Brawl', N'Wii', 12.84)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (12, N'Super Mario Galaxy', N'Wii', 11.35)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (13, N'Just Dance 3', N'Wii', 10.12)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (14, N'Just Dance 2', N'Wii', 9.44)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (15, N'Wii Party', N'Wii', 8.38)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (17, N'Mario & Sonic at the Olympic Games', N'Wii', 7.99)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (18, N'Super Mario Galaxy 2', N'Wii', 7.51)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (20, N'Super Mario Bros', N'NES', 40.24)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (21, N'Duck Hunt', N'NES', 28.31)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (22, N'Super Mario Bros. 3', N'NES', 17.28)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (23, N'Super Mario Bros', N'NES', 7.45)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (24, N'Pokemon Red/Pokemon Blue', N'GameBoy', 31.37)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (25, N'Tetris', N'GameBoy', 30.26)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (26, N'Pokemon Gold/Pokemon Silver', N'GameBoy', 23.1)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (27, N'Super Mario Land', N'GameBoy', 18.14)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (28, N'Pokémon Yellow: Special Pikachu Edition', N'GameBoy', 14.64)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (29, N'Super Mario Land 2: 6 Golden Coins', N'GameBoy', 11.18)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (30, N'New Super Mario Bros', N'Nintendo DS', 29.8)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (31, N'Nintendogs', N'Nintendo DS', 24.67)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (32, N'Mario Kart DS', N'Nintendo DS', 23.21)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (33, N'Brain Age: Train Your Brain in Minutes a Day', N'Nintendo DS', 20.15)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (34, N'Pokemon Diamond/Pokemon Pearl', N'Nintendo DS', 18.25)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (35, N'Brain Age 2: More Training in Minutes a Day', N'Nintendo DS', 15.29)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (36, N'Pokemon Black/Pokemon White', N'Nintendo DS', 15.14)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (37, N'Animal Crossing: Wild World', N'Nintendo DS', 12.13)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (38, N'Pokemon HeartGold/Pokemon SoulSilver', N'Nintendo DS', 11.77)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (39, N'Super Mario 64', N'Nintendo DS', 10.3)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (40, N'Mario Party DS', N'Nintendo DS', 8.91)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (41, N'Pokemon Black 2/Pokemon White 2', N'Nintendo DS', 8.07)
INSERT INTO [dbo].[Game] ([Id], [Name], [Catagory], [Value]) VALUES (42, N'Pokémon Platinum Version"', N'Nintendo DS', 7.72)
SET IDENTITY_INSERT [dbo].[Game] OFF
